ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-nbconvert
    rev: v6.0.4
    hooks:
      - id: nbconvert
