site_name: ATOM
site_author: Mavs
site_url: https://tvdboom.github.io/ATOM
repo_name: tvdboom/ATOM
repo_url: https://github.com/tvdboom/ATOM
edit_uri: edit/master/docs_sources/
docs_dir: docs_sources/
site_dir: docs/
copyright: Copyright &copy; 2019-2024, by Mavs.

theme:
    name: material
    logo: img/icon_white.png
    favicon: img/favicon.ico
    custom_dir: docs_sources/overrides
    features:
        - content.action.edit
        - content.action.view
        - content.code.copy
        - navigation.footer
        - navigation.instant
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - content.tabs.link
        - announce.dismiss
        - toc.follow
        - search.suggest
    palette:
        # Light mode
        - amber: "(prefers-color-scheme: light)"
          scheme: default
          primary: teal
          accent: teal
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode

        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: teal
          accent: teal
          toggle:
              icon: material/weather-night
              name: Switch to light mode

extra:
    analytics:
        provider: google
        property: !ENV GOOGLE_ANALYTICS_KEY
    version:
        provider: mike
    social:
        - icon: fontawesome/brands/slack
          link: https://app.slack.com/client/T02BXTWUB5Y/C02BUTT7PV3
          name: Slack
        - icon: fontawesome/brands/github
          link: https://github.com/tvdboom/ATOM
          name: GitHub
        - icon: fontawesome/brands/stack-overflow
          link: https://stackoverflow.com/questions/tagged/atom-ml
          name: StackOverflow
        - icon: fontawesome/brands/python
          link: https://pypi.org/project/atom-ml/
          name: Pypi
        - icon: fontawesome/brands/medium
          link: https://tvdboom.medium.com/
          name: Medium
        - icon: fontawesome/solid/envelope
          link: mailto:m.524687@gmail.com
          name: Email

plugins:
    - search
    - autorefs
    - mkdocs-jupyter:
          include_requirejs: true
          include: ["*.ipynb"]
          include_source: true
          ignore_h1_titles: true
    - mkdocs-simple-hooks:
          hooks:
              on_page_markdown: docs_sources.scripts:render
              on_page_content: docs_sources.scripts:corrections
              on_post_build: docs_sources.scripts:clean_search
    - git-revision-date-localized:
          enable_creation_date: true
          fallback_to_build_date: true
          enabled: !ENV [CI, false]
    - git-committers:
          repository: tvdboom/ATOM
          branch: master
          token: ${{ secrets.GITHUB_TOKEN }}

markdown_extensions:
    - admonition
    - md_in_html  # Allows for writing Markdown inside HTML
    - def_list  # Allows for definition lists (e.g., nomenclature)
    - attr_list  # Allows for HTML attributes and CSS classes to markdown objects
    - footnotes
    - pymdownx.details  # Allows for collapsible admonition blocks
    - pymdownx.magiclink  # Allows for bare links of the form <url>
    - pymdownx.inlinehilite  # Allows for inline highlighting of code blocks
    - pymdownx.superfences:
        preserve_tabs: true
        custom_fences:
            - name: python
              class: python
              format: !!python/name:docs_sources.scripts.formatter
    - pymdownx.arithmatex:  # Allows for rendering of equations
          generic: true
    - pymdownx.tabbed:  # Allows the usage of content tabs
          alternate_style: true
    - pymdownx.emoji:  # Automatically inlines bundled and custom icons and emojis
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:  # Allows for highlighting of code blocks
          use_pygments: true
          pygments_lang_class: true
          linenums: true
          linenums_style: pymdownx-inline

extra_css:
    - stylesheets/extra.css

extra_javascript:
    - stylesheets/extra.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # MathJax

nav:
    - About: about.md
    - Getting started: getting_started.md
    - User guide:
        - Introduction: user_guide/introduction.md
        - Nomenclature: user_guide/nomenclature.md
        - Data management: user_guide/data_management.md
        - Logging & Tracking: user_guide/logging.md
        - Accelerating pipelines: user_guide/accelerating.md
        - Data cleaning: user_guide/data_cleaning.md
        - Feature engineering: user_guide/feature_engineering.md
        - NLP: user_guide/nlp.md
        - Time Series: user_guide/time_series.md
        - Models: user_guide/models.md
        - Training: user_guide/training.md
        - Predicting: user_guide/predicting.md
        - Plots: user_guide/plots.md
    - API:
        - ATOM:
            - ATOMClassifier: api/atom/atomclassifier.md
            - ATOMForecaster: api/atom/atomforecaster.md
            - ATOMModel: api/atom/atommodel.md
            - ATOMRegressor: api/atom/atomregressor.md
        - Branch:
            - Branch: api/branch/branch.md
            - BranchManager: api/branch/branchmanager.md
        - Data cleaning:
            - Balancer: api/data_cleaning/balancer.md
            - Cleaner: api/data_cleaning/cleaner.md
            - Decomposer: api/data_cleaning/decomposer.md
            - Discretizer: api/data_cleaning/discretizer.md
            - Encoder: api/data_cleaning/encoder.md
            - Imputer: api/data_cleaning/imputer.md
            - Normalizer: api/data_cleaning/normalizer.md
            - Pruner: api/data_cleaning/pruner.md
            - Scaler: api/data_cleaning/scaler.md
        - Feature engineering:
            - FeatureExtractor: api/feature_engineering/featureextractor.md
            - FeatureGenerator: api/feature_engineering/featuregenerator.md
            - FeatureGrouper: api/feature_engineering/featuregrouper.md
            - FeatureSelector: api/feature_engineering/featureselector.md
        - NLP:
            - TextCleaner: api/nlp/textcleaner.md
            - TextNormalizer: api/nlp/textnormalizer.md
            - Tokenizer: api/nlp/tokenizer.md
            - Vectorizer: api/nlp/vectorizer.md
        - Training:
            - DirectClassifier: api/training/directclassifier.md
            - DirectForecaster: api/training/directforecaster.md
            - DirectRegressor: api/training/directregressor.md
            - SuccessiveHalvingClassifier: api/training/successivehalvingclassifier.md
            - SuccessiveHalvingForecaster: api/training/successivehalvingforecaster.md
            - SuccessiveHalvingRegressor: api/training/successivehalvingregressor.md
            - TrainSizingClassifier: api/training/trainsizingclassifier.md
            - TrainSizingForecaster: api/training/trainsizingforecaster.md
            - TrainSizingRegressor: api/training/trainsizingregressor.md
        - Models:
            - AdaBoost: api/models/adab.md
            - ARIMA: api/models/arima.md
            - AutoARIMA: api/models/autoarima.md
            - AutoETS: api/models/autoets.md
            - AutomaticRelevanceDetermination: api/models/ard.md
            - Bagging: api/models/bag.md
            - BATS: api/models/bats.md
            - BayesianRidge: api/models/br.md
            - BernoulliNB: api/models/bnb.md
            - CatBoost: api/models/catb.md
            - CategoricalNB: api/models/catnb.md
            - ComplementNB: api/models/cnb.md
            - Croston: api/models/croston.md
            - DecisionTree: api/models/tree.md
            - Dummy: api/models/dummy.md
            - DynamicFactor: api/models/df.md
            - ElasticNet: api/models/en.md
            - ETS: api/models/ets.md
            - ExponentialSmoothing: api/models/es.md
            - ExtraTree: api/models/etree.md
            - ExtraTrees: api/models/et.md
            - GaussianNB: api/models/gnb.md
            - GaussianProcess: api/models/gp.md
            - GradientBoostingMachine: api/models/gbm.md
            - HuberRegression: api/models/huber.md
            - HistGradientBoosting: api/models/hgbm.md
            - KNearestNeighbors: api/models/knn.md
            - Lasso: api/models/lasso.md
            - LeastAngleRegression: api/models/lars.md
            - LightGBM: api/models/lgb.md
            - LinearDiscriminantAnalysis: api/models/lda.md
            - LinearSVM: api/models/lsvm.md
            - LogisticRegression: api/models/lr.md
            - MSTL: api/models/mstl.md
            - MultiLayerPerceptron: api/models/mlp.md
            - MultinomialNB: api/models/mnb.md
            - NaiveForecaster: api/models/nf.md
            - OrdinaryLeastSquares: api/models/ols.md
            - OrthogonalMatchingPursuit: api/models/omp.md
            - PassiveAggressive: api/models/pa.md
            - Perceptron: api/models/perc.md
            - PolynomialTrend: api/models/pt.md
            - Prophet: api/models/prophet.md
            - QuadraticDiscriminantAnalysis: api/models/qda.md
            - RadiusNearestNeighbors: api/models/rnn.md
            - RandomForest: api/models/rf.md
            - Ridge: api/models/ridge.md
            - SARIMAX: api/models/sarimax.md
            - StochasticGradientDescent: api/models/sgd.md
            - STL: api/models/stl.md
            - SupportVectorMachine: api/models/svm.md
            - TBATS: api/models/tbats.md
            - Theta: api/models/theta.md
            - VAR: api/models/var.md
            - VARMAX: api/models/varmax.md
            - XGBoost: api/models/xgb.md
        - Pipeline:
            - Pipeline: api/pipeline/pipeline.md
        - Plots:
            - plot_acf: api/plots/plot_acf.md
            - plot_bootstrap: api/plots/plot_bootstrap.md
            - plot_calibration: api/plots/plot_calibration.md
            - plot_ccf: api/plots/plot_ccf.md
            - plot_components: api/plots/plot_components.md
            - plot_confusion_matrix: api/plots/plot_confusion_matrix.md
            - plot_correlation: api/plots/plot_correlation.md
            - plot_cv_splits: api/plots/plot_cv_splits.md
            - plot_data_splits: api/plots/plot_data_splits.md
            - plot_decomposition: api/plots/plot_decomposition.md
            - plot_det: api/plots/plot_det.md
            - plot_distribution: api/plots/plot_distribution.md
            - plot_edf: api/plots/plot_edf.md
            - plot_errors: api/plots/plot_errors.md
            - plot_evals: api/plots/plot_evals.md
            - plot_feature_importance: api/plots/plot_feature_importance.md
            - plot_fft: api/plots/plot_fft.md
            - plot_forecast: api/plots/plot_forecast.md
            - plot_gains: api/plots/plot_gains.md
            - plot_hyperparameter_importance: api/plots/plot_hyperparameter_importance.md
            - plot_hyperparameters: api/plots/plot_hyperparameters.md
            - plot_learning_curve: api/plots/plot_learning_curve.md
            - plot_lift: api/plots/plot_lift.md
            - plot_ngrams: api/plots/plot_ngrams.md
            - plot_pacf: api/plots/plot_pacf.md
            - plot_parallel_coordinate: api/plots/plot_parallel_coordinate.md
            - plot_pareto_front: api/plots/plot_pareto_front.md
            - plot_parshap: api/plots/plot_parshap.md
            - plot_partial_dependence: api/plots/plot_partial_dependence.md
            - plot_pca: api/plots/plot_pca.md
            - plot_periodogram: api/plots/plot_periodogram.md
            - plot_permutation_importance: api/plots/plot_permutation_importance.md
            - plot_pipeline: api/plots/plot_pipeline.md
            - plot_prc: api/plots/plot_prc.md
            - plot_probabilities: api/plots/plot_probabilities.md
            - plot_qq: api/plots/plot_qq.md
            - plot_relationships: api/plots/plot_relationships.md
            - plot_residuals: api/plots/plot_residuals.md
            - plot_results: api/plots/plot_results.md
            - plot_rfecv: api/plots/plot_rfecv.md
            - plot_roc: api/plots/plot_roc.md
            - plot_series: api/plots/plot_series.md
            - plot_shap_bar: api/plots/plot_shap_bar.md
            - plot_shap_beeswarm: api/plots/plot_shap_beeswarm.md
            - plot_shap_decision: api/plots/plot_shap_decision.md
            - plot_shap_force: api/plots/plot_shap_force.md
            - plot_shap_heatmap: api/plots/plot_shap_heatmap.md
            - plot_shap_scatter: api/plots/plot_shap_scatter.md
            - plot_shap_waterfall: api/plots/plot_shap_waterfall.md
            - plot_slice: api/plots/plot_slice.md
            - plot_successive_halving: api/plots/plot_successive_halving.md
            - plot_terminator_improvement: api/plots/plot_terminator_improvement.md
            - plot_timeline: api/plots/plot_timeline.md
            - plot_threshold: api/plots/plot_threshold.md
            - plot_trials: api/plots/plot_trials.md
            - plot_wordcloud: api/plots/plot_wordcloud.md
    - Examples:
        - Accelerating cuml: examples/accelerating_cuml.ipynb
        - Accelerating sklearnex: examples/accelerating_sklearnex.ipynb
        - Advanced plotting: examples/advanced_plotting.ipynb
        - Automated feature scaling: examples/automated_feature_scaling.ipynb
        - Binary classification: examples/binary_classification.ipynb
        - Bootstrapping: examples/bootstrapping.ipynb
        - Calibration: examples/calibration.ipynb
        - Data engines: examples/data_engines.ipynb
        - Deep learning: examples/deep_learning.ipynb
        - Ensembles: examples/ensembles.ipynb
        - Feature engineering: examples/feature_engineering.ipynb
        - Getting started: examples/getting_started.ipynb
        - Holdout set: examples/holdout_set.ipynb
        - Hyperparameter tuning: examples/hyperparameter_tuning.ipynb
        - Imbalanced datasets: examples/imbalanced_datasets.ipynb
        - In-training validation: examples/in_training_validation.ipynb
        - Memory considerations: examples/memory_considerations.ipynb
        - Metadata: examples/metadata.ipynb
        - Multi-metric runs: examples/multi_metric.ipynb
        - Multiclass classification: examples/multiclass_classification.ipynb
        - Multilabel classification: examples/multilabel_classification.ipynb
        - Multioutput regression: examples/multioutput_regression.ipynb
        - Multivariate forecast: examples/multivariate_forecast.ipynb
        - NLP: examples/nlp.ipynb
        - Pruning: examples/pruning.ipynb
        - Ray backend: examples/ray_backend.ipynb
        - Regression: examples/regression.ipynb
        - Successive halving: examples/successive_halving.ipynb
        - Train sizing: examples/train_sizing.ipynb
        - Univariate forecast: examples/univariate_forecast.ipynb
        - Utilities: examples/utilities.ipynb
    - Changelog:
        - v6.x.x: changelog/v6.x.x.md
        - v5.x.x: changelog/v5.x.x.md
        - v4.x.x: changelog/v4.x.x.md
    - FAQ: faq.md
    - Contributing: contributing.md
    - Dependencies: dependencies.md
    - License: license.md
